### ISSUE TITLE
Expiry date on new access token

### ISSUE THREAD

**Issue by reggi** [jfromaniello/refresh-token#2]
All that is returned is a new token with no expiry date. It would be nice to get it from the source.

**Comment by jfromaniello** [comment]
You can use `tokenProvider.currentToken.expires_in_date`, this will give you the date when the token is going to expire.

The goal of this module is to give you a valid token always.. if the token is not expired it will return the current token, if is expired it fetchs a new token

**Comment by reggi** [comment]
Thanks @jfromaniello!
